services:
  app:
    container_name: ${ALIAS}
    restart: always
    image: '${ALIAS}-image'
    volumes:
      - ./data/datastore.json:/usr/project/datastore.json
      - ./data/cache:usr/project/cache
    environment:
      - DISCORD_TOKEN

    entrypoint: /usr/project/app