# Professional release workflow for Go multi-platform binaries
#
# On new tag, builds binaries for major OS/arch, attaches to GitHub Release named after the tag.

name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: darwin
            goarch: arm64 # Only build darwin/arm64 if needed, comment out to enable
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -trimpath -ldflags="-s -w" -o dist/melodix-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/melodix
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/melodix-${{ matrix.goos }}-${{ matrix.goarch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
